### ISSUE TITLE
Build is broken on current master

### ISSUE THREAD

**Issue by KingDuckZ** [ThePhD/out_ptr#2]
I hate to be that guy again, but [this line](https://github.com/ThePhD/out_ptr/blob/master/include/phd/detail/base_inout_ptr_impl.hpp#L49) is breaking the build as soon as I include out_ptr's headers in my project. Note that static_assert(false) will *always*. See [StackOverflow](https://stackoverflow.com/questions/14637356/static-assert-fails-compilation-even-though-template-function-is-called-nowhere#14637534) for more details.

**Comment by ThePhD** [comment]
Thanks for reporting! This bug is gone now; sorry about that.

Published in latest release, https://github.com/ThePhD/out_ptr/releases/tag/v1.0.2
